name: 'techstore_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'techstore_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  techstore_dbt:
    +schema: staging
    sale_dates:
      +column_types:
        SALE_DATE: date
        NAME: varchar
        DISCOUNT_PERCENT: numeric(18,2)

vars:
  default_date: '9999-01-01'

on-run-start: 
  - "{{ audit_prep() }}"
  - "{{ audit_log('run_start') }}"
on-run-end: 
  - "{{ audit_log('run_end') }}"

# Configuring models
models:
  techstore_dbt:
    +pre-hook: 
      - "{{ log('THIS IS A PRE-HOOK') }}"
      - "{{ audit_log('model_start') }}"
    +post-hook: 
      - "{{ log('THIS IS A POST-HOOK') }}"
      - "{{ audit_log('model_end') }}"
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
      +tags:
        - p1
    utilities:
      +materialized: table
      +schema: utilities