techstore_dbt:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_032
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_032
      schema: dbt_jpatel
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_032
    ci:
      account: yl45797.east-us-2.azure
      database: analytics_032
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_032
      schema: dbt_ci  # QA/UAT/etc.
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_032
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_032
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_032
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_032
  target: dev



